development: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: nightingale-dev

test:
  <<: *default
  database: nightingale-test

production:
  <<: *default
  database: nightingale-production