development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  password: barc3l0na
  username: postgres

production:
  <<: *default
  database: contactlens_production

development:
  <<: *default
  database: contactlens_development

test:
  <<: *default
  database: contactlens_test