development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: barc3l0na
iushushfd
production:
  <<: *default
  database: contactlens_production

development:
  <<: *default
  database: contactlens_development

test:
  <<: *default
  database: contactlens_test